In [1]:
'''
EXERCISE: "Human Learning" with iris data
'''
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
# load the famous iris data
iris = load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [3]:
type(iris.data)

numpy.ndarray

In [4]:
# what do you think these attributes represent?
iris.data[:5,]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [5]:
iris.data.shape

(150, 4)

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [ ]:
# intro to numpy
type(iris.data)

In [9]:
## PART 1: Read data into pandas and explore
pd.DataFrame(iris.data).head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [10]:
iris.feature_names
# the feature_names are a bit messy, let's 
# clean them up. remove the (cm)
# at the end and replace any spaces with an underscore
# create a list called "features" that 
# holds the cleaned column names
features = [i.replace(' ','_')[:-5] for i in iris.feature_names]# <FILL IN>
features

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [12]:
# read the iris data into pandas, with our refined column names
df = pd.DataFrame(iris.data, columns=features)

In [13]:
#df.head()
df.as_matrix()

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [15]:
# EXERCISEEE

# create a list of species (should be 150 elements) 
# using iris.target and iris.target_names
# resulting list should only have the words "setosa", "versicolor", and "virginica"
'''
species ==  
['setosa',
 'setosa',
 'setosa',
 'setosa',
...
...
 'virginica',
 'virginica']

Hint: use the iris.target_names and iris.target arrays
'''
species = [i.target for i in iris.target_names]












AttributeError: 'numpy.string_' object has no attribute 'target'

In [ ]:
# ANSWERRRR


species = [iris.target_names[i] for i in iris.target]
list(iris.target_names[iris.target])

In [ ]:
# add the species list as a new DataFrame column
df['species'] = species
df.head()

In [ ]:
# explore data numerically, looking for differences between species
# try grouping by species and check out the different predictors
# explore data numerically, looking for differences between species
df.describe()
df.groupby('species').describe()

In [ ]:
df.groupby('species').sepal_length.mean()

In [ ]:
df.groupby('species')['sepal_length', 'sepal_width', 'petal_length', 'petal_width'].mean()

In [ ]:
'''
agg is a new function we haven't seen yet. It will
aggregate each column using specified lists of functions.
We have been using some of its shortcuts but using
agg allows us to put in many functions at a time

df.groupby('species').agg(np.mean)
==
df.groupby('species').mean()

BUT 
df.groupby('species').agg([np.min, np.max])

doesn't have a short form
'''

df.groupby('species').agg([np.min, np.max, np.mean, np.std])


In [ ]:
color_map = {
    'versicolor': 'r',
    'setosa': 'b',
    'virginica': 'g'
}
colors = [color_map[s] for s in df['species']]
pd.scatter_matrix(df, color=colors, figsize=(10,10))

In [ ]:
# parallel coordinates help us visualize multivariate data

from pandas.tools.plotting import parallel_coordinates
parallel_coordinates(df, 'species')

In [ ]:
# I used values in order to see all of the data at once
# without .values, a dataframe is returned


## PART 2: Write a function to predict the species for each observation


### EXERCISE!!!!! ###

# note data must be in order
# ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

# define a function that takes in a row of data and returns a predicted species
def classify_iris(data):
    if False and False or False and False:
        return 'rose'
    elif False and (True or False):
        return 'lily'
    else:
        return 'I have no clue'

# example use
classify_iris([3.4, 5.4, 7.5, 2.3])

In [ ]:
def test_my_function(func):
    # make predictions and store as numpy array
    preds = np.array([func(row) for row in df.values])
    # calculate the accuracy of the predictions
    return np.mean(preds == df.species.values)

In [ ]:
test_my_function(classify_iris)

In [ ]:
# EXAMPLEE using only petal_width
def hunter_classify_iris(data):
    if data[3] < 3:
        return 'setosa'
    else:
        return None


In [ ]:
test_my_function(hunter_classify_iris) # TRY AND BEAT ME